### ISSUE TITLE
ZIM backend : read CSS/JS/image dependencies inside the ZIM file, and inject them in the article content with a service-worker

### ISSUE THREAD

**Issue by mossroy** [mossroy/evopedia-html5#115]
A ZIM file might contain any type of content.
A content might use some dependencies like images, CSS stylesheets, javascript files etc. These dependencies are in the ZIM file too.

When that happens, we need to read them, and inject them inside the article

**Comment by mossroy** [comment]
Some prorotype work is started in the "serviceworker_in_frame" branch.
It raised some difficulties :
- need to activate the service worker feature manually with a setting in Firefox : dom.serviceWorkers.enabled=true. In Firefox OS Simulator, it has to be set in the pref.js
- lack of debug tools (Chromium has more)
- does not work on a file:// URL, even on Firefox Nightly (workaround : expose through localhost with a local web server). On Firefox OS, when deploying it inside an app, it does not work in versions <=2.2. But it works on 3.0 (in the Simulator)
- trap : a serviceworker catches (by default) all the URLs of its path depth. So it has to be put at the right level. We need to be careful because it can also capture the main index.html file itself...
- trap : in Chromium/Chrome, the service workers do not always update if you change the code and reload the page. Workaround : unregister them in chrome://serviceworker-internals/. In Firefox, you need to restart Firefox (and not restore previous session)

**Comment by mossroy** [comment]
Just commited some more prototype testing, that makes sure we manage to inject binary data in the article (an image, here)
TODO :
- reduce the scope of the serviceworker, so that it only intercepts the content of articles (and dependencies), and not the UI
- block the application before the SW is ready
- plug the SW with the backend, so that to effectively read content from there, instead of the hard-coded ones from the prototype
- re-enable the jQuery stuff for Evopedia archives, and maybe register the SW only for ZIM archives

Another trap : in Chromium/Chrome, the first displayed page dependencies are not intercepted by the SW. You need to reload the page first. This issue does not happen on Firefox nightly

**Comment by mossroy** [comment]
There is a technical difficulty to read the backend from the ServiceWorker.
When testing the app inside a desktop browser, the archive file(s) are given by the user through an input type="file". And I don't see how to pass them to the ServiceWorker.
Service Workers are isolated : they can not access the DOM for example. You can communicate with them through text messages, but it does not seem possible to share such objects with them.

So I'll try another approach : make the Service Worker send a message to app.js (like "give me this content"), so that it reads the backend, and gives the result back to the ServiceWorker (through another message)
Pro : I don't have to instanciate the archive twice (outside and inside the ServiceWorker), and it will work in any case
Con : I will have to pass the content through messages to the ServiceWorker : I hope it will not give performance issues, and will work for binary contents (without converting them to base64)

**Comment by kelson42** [comment]
Why not simply pushing the ZIM local path to the serviceworker as a string and let it open/deal with it?

**Comment by mossroy** [comment]
That might work when using the DeviceStorage API or the Cordova API (it needs to be tested for both)
But I don't think it would work when using a desktop browser : in this case, it's the DOM that gives a File instance. A browser should not allow some javascript code to open a File on the user filesystem (for security reasons), and I don't know an API that would do that (even the FileSystem API can not https://developer.mozilla.org/en-US/docs/Web/API/FileSystem)

But there might be a workaround : it looks like the postMessage API allows to "transfer" some objects to the ServiceWorker : http://www.w3.org/TR/service-workers/#service-worker-postmessage
It might allow to transfer the File instance to the ServiceWorker. But, if I understood correctly, it's a real transfer in the sense that the instance is not available any more in the caller context. So that would force to do all the backend work in the ServiceWorker (which might be complicated for title search for example)

I need to find some time to test these ideas

**Comment by mossroy** [comment]
It does not seem to be possible to transfer our archive file to the ServiceWorker through a postMessage call.
According to https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage , you can only transfer "Transferable" objects, which are, for now, only ArrayBuffer and MessagePort objects.
I tested and it indeed does not work.

So we still have at least 2 possibilities to implement this serviceworker :
- keep the backend in app.js, and communicate with the serviceworker through messages. I've started working on that, but it's not so easy
- let the serviceworker instanciate the backend as suggested by @kelson42 , and give up compatibility with desktop browsers. It's true that they are not the main target, but they are very convenient for developing/testing. In particular, it's precious to be able to use the Chromium/Chrome serviceworker debug tools that do not exist yet on Firefox/Firefox OS

**Comment by mossroy** [comment]
Regarding performance of communication between the Service Worker and the main thread, I read https://hacks.mozilla.org/2015/07/how-fast-are-web-workers/
It seems to be fast enough (in our use cases) to avoid frame drops in the UI.
It should even be possible to transfer the contents through ArrayBuffers, instead of copying them, which should speed up the communication.

**Comment by kelson42** [comment]
FYI, so we will need to wait at least 2 months more to have it (as stable feature) in Firefox https://blog.wanderview.com/blog/2015/06/18/service-workers-will-not-ship-in-firefox-41/

**Comment by mossroy** [comment]
Thanks for the reference.
It looks like good news to me, because it at least gives an idea of the period when it might be available by default.

**Comment by mossroy** [comment]
I made some progress on that feature, even if it's still in a "quick and dirty" way. It's commited in the "serviceworker_in_frame" branch.
I now manage to have a bi-directional communication between the ServiceWorker and the backend (through app.js). But it involves using another extra API : https://developer.mozilla.org/fr/docs/Web/API/MessageChannel , which is also disabled by default in Firefox for now. See http://caniuse.com/#search=messagechannel . So we also need to enable it manually in Firefox.

What works for now : 
- communication between the ServiceWorker and app.js. It allows us to test/debug on desktop browsers, with all the comfort that comes with
- hypertext links to articles (but some of them still display a white page. I suppose it's a backend issue because redirects are handled)
- displaying a dummy image for all JPEG images embedded in the articles

What does not work : 
- reading contents other than articles from the backend (which means no CSS/JS/etc for now)
- starting a new search
- on first load, nothing is displayed because the ServiceWorker is not yet available. You need to reload the page to get it working
- probably many other things

What needs to be improved : 
- find a better way to wait for the serviceworker to be ready before sending the init message (to initialize the messageChannel). For now, it's done when opening the first article
- read all the contents from the backend, and properly handle their MIME types
- some refactoring in app.js to use the Promise API (see #67 )

How to make it work on Firefox (only nightly for now?) : 
- both preferences "dom.serviceWorkers.enabled" and "dom.messageChannel.enabled" should be set to true. It seems to be the case by default in Nightly 42. Else you have to set them in prefs.js (inside the Firefox profile), or in about:config
- when you modify the serviceworker code, you need to unregister it manually in Firefox, so that the new version is loaded. It can be done by going into the page info -> permissions, and click on "Clear storage" in the "Maintain offline storage" line
- you can't open the index.html file directly from the filesystem, else the ServiceWorker won't accept to load with a "SecurityError: The operation is insecure". You need to open it through a web server on localhost (or from a remote server, but in this case, you'll need to use https)
- you can see the logs of the Service Worker : in the console, you need to tick the "Service Workers" item in the Logging category (note that it can significantly slow down the browser if you activate all the logs)

Platforms tested for now : 
- Chromium 43 : works properly. You need to reload the page the first time, and use a local webserver, as for Firefox
- Firefox nightly (42) : works properly. See above
- Firefox OS Simulator 3.0 (based on Gecko 41, dated 26 May 2015) : does not work (UI seems frozen, I don't know why. But, last time I checked, it managed to register the ServiceWorker : I'll have to check again when a newer version is available)
- Firefox OS Simulator 2.2 (based on Gecko 37) : does not work (Security Error when trying to register the ServiceWorker : I suppose it's because it's a local file)
- Flatfish tablet with Firefox OS 3.0-prerelease (based on Gecko 40.0a1, dated 8 May 2015) : does not work (no article displayed)

**Comment by mossroy** [comment]
The code falls back to the previous behavior (jQuery injection) when the ServiceWorker API or MessageChannel API is unavailable. And the iframe works not so bad.
So I've merged both branches to master : I don't think it's necessary to keep this work separate any more, and it will avoid merges between these branches.

**Comment by mossroy** [comment]
I managed to debug what happens on the tablet with Firefox OS 3.0-reprelease (from May 2015) : there is a DataCloneError when trying to initiate the communication channel with the ServiceWorker : "The object could not be cloned", regarding the MessagePort we try to transfer to the ServiceWorker.
This looks like a bug in FirefoxOS.
Hopefully it might already be resolved, but I can't check for now because all the more recent nightly builds I have (in the Simulator or on a Peak device) are broken on the DeviceStorage access : you can't read the SD-card at all...

**Comment by mossroy** [comment]
Quick update on the status of the app on Firefox OS versions : 
The DataCloneError found in version nightly from May 2015 (see above comment) has probably been fixed as I do not encounter it any more on more recent versions.
The "frozen UI" has been fixed in the code : it was due to some cordova javascript, that isn't used for now : I've commented it.

On a recent Nightly build (from today : 2015-09-20) on a Peak device, the messageChannel API is available by default, but not the serviceWorker API.
So, by default, it falls back to jQuery injection, and works well (without any images/javascript/css etc)
If you manually enable the serviceWorker API, the service worker is registered and runs. As on desktop browser, it does not work on the first time : you need to close the app and open it again to have it working.
Unfortunately, the UI freezes after displaying a first article (probably a javascript error but I could not find where)

**Comment by mossroy** [comment]
It now works without modifying any settings on Firefox dev edition https://www.mozilla.org/en-US/firefox/developer/ (at least current version : 43.0a2 2015-10-16). You still need to access the files through a webserver, and to reload the page after the first opening. But it's clearly more convenient for testing than a nightly version because the dev edition does not pollute your Firefox profile as a nightly would do : it uses a separate profile.

**Comment by kelson42** [comment]
This is really a good news, I guess that means that next FFOS release/upgrade will be at the same level?
Do we have otherwise ticket links to Mozilla bugtracker for the two last FFOS blockers? IMO this would be really important to have them to try to push a little their respective fixes.

**Comment by mossroy** [comment]
Yes, but it's a bit more complicated.

It's good news because it means that the implementation is almost ready in Gecko, and that Mozilla is testing to enable serviceworkers by default (messagechannels are already enabled by default in stable release).
But that does not mean that next Firefox stable version will have serviceworkers enabled. It might take some more time. For example, Electrolysis (multi-threading in Firefox) is enabled by default in dev edition, to help testing it. But it will probably not be enabled soon in a stable release.

FFOS is based on the same Gecko engine, so everything will finally end up in it. But it will take more time because a stable FFOS version is always based on an older Gecko version : See https://en.wikipedia.org/wiki/Firefox_OS#Release_history

Regarding Firefox OS, I tested yesterday with a nightly version (based on Gecko 44.0a1). Serviceworkers are not enabled by default on it. After manually enabling it, I still face the UI freeze after displaying the first article. I have to figure out what's going on : it might simply be a bug in our code that does not trigger on desktop. But I lack time to investigate those weeks...

Regarding the 2 other issues :
- having to reload the page (or close/reopen the application) : It's a real problem, but I don't think it's a Gecko bug, because the behavior is the same on Chromium/Chrome. We'll have to investigate to see if we can find a workaround (like programmatically reloading : https://developer.mozilla.org/en-US/docs/Web/API/Window/location#Example_2_Force_reloading_the_current_page_from_the_server ) and/or ask for an enhancement.
- having to use a webserver instead of simply file:/// URLs is not a big issue IMHO. First because it does not occur within a Firefox OS application, which is the main target. It's a bit annoying when developing, but IDEs like Netbeans can handle it quite nicely.

**Comment by mossroy** [comment]
I think that the "frozen" UI comes from dependencies of the article that the service worker is not able to respond to.
I just commited a fix to send a dummy content for javascript requests, and it allows to display some articles on Firefox OS nightly (20151122180628 : v2.6 nightly, based on gecko 45.0a1), which is great news!
The dummy images sent by the service worker are also displayed, which means that the service worker is working fine.

If it's "only" a problem of missing content, I suppose it will be resolved when we'll be able to read everything from the backend

**Comment by mossroy** [comment]
I think we can consider this feature implemented, event if it's certainly still buggy.
It works for CSS and images, at least on the Ray Charles archive, both in ServiceWorker and jQuery modes.
I postponed the javascript content injection in #152

For the record, Service Worker activation by default is supposed to land in Firefox 44 or 45.
For Firefox OS, it won't be in 2.5 : hopefully in 2.6. See the tracking bug https://bugzilla.mozilla.org/show_bug.cgi?id=1131322
